spring:
  application:
    name: file-storage-rest-api
    servlet:
      multipart:
        enabled: true
        file-size-threshold: 4K
        max-file-size: 10MB
        max-request-size: 12MB
server:
  port: 56777
fs-repo:
  root-dir: C:/Temp/repo

